---
### Generic smell configuration

detectors:
  FeatureEnvy:
    exclude:
      - "IMDb::Title#casts"
      - "IMDb::Title#directors"
  DuplicateMethodCall:
    exclude:
      - "Exceptions#test_invalid_url"
  TooManyStatements:
    max_statements: 10
