###########################
# Configuration for rubocop
# in .rubocop.yml
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidelines for contributions.
#
# Any of these may be changed.
AllCops:
  TargetRubyVersion: "3.0.0"
  NewCops: enable

StringLiterals:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

Style/ClassVars:
  Enabled: false
