###########################
# Configuration for rubocop
# in .rubocop.yml
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidelines for contributions.
#
# Any of these may be changed.
require:
  - rubocop-minitest
  - rubocop-rake
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: "3.0.0"
  NewCops: enable
  Exclude:
    - "test.rb"
